version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5433:5432"
    volumes:
      - ./data/postgres:/data/postgres
    env_file:
      - docker.env
 
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - docker.env
    depends_on:
      - postgres

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    hostname: rabbitmq
    volumes:
      - /var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - ./rabbitmq.env

  face:
    build:
      context: .
      dockerfile: ./apps/face/Dockerfile
      target: development
    command: npm run start:dev face
    env_file:
      - ./apps/face/.env
    depends_on:
      - rabbitmq
    environment:
      WATCHPACK_POLLING: "true"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '5000:5000'

  aws:
    build:
      context: .
      dockerfile: ./apps/aws/Dockerfile
      target: development
    command: npm run start:dev aws
    env_file:
      - ./apps/aws/.env
    depends_on:
      - rabbitmq
    environment:
      WATCHPACK_POLLING: "true"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '5001:5001'

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "path.repo=/usr/src/app/elasticsearch/data"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/src/app/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "path.repo=/usr/src/app/elasticsearch/data"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data02:/usr/src/app/elasticsearch/data

  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    container_name: es03
    environment:
      - node.name=es03
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "path.repo=/usr/src/app/elasticsearch/data"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data03:/usr/src/app/elasticsearch/data

volumes:
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local